config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   
	post 'create_qrcode', to: 'users#create_qrcode'
	post 'log_in', to: 'users#log_in'
	post 'log_out', to: 'users#log_out'
	resources :users
	resources :cases
	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
	belongs_to :user
	has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :case
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :cases
	
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController

	def index
	end

	def create
		# Creating case that links to the user directly
		# Given case type and serial number
		@case=current_user.cases.new(get_params)
		if @case.save

			# if case is save, only assign serial number.
			@case.serial_number = "ORTHO"+ @case.case_type.to_s + "-" +@case.id.to_s			
			@case.save
			
			crowns= ["Get 3d scan", "make mould","cast","milling","oven dry"]
			retainers =["Get 3d scan", "make mould","cast","milling","oven dry"]
			braces = ["Get 3d scan", "make mould","cast","milling","oven dry"]
			babies =["Get 3d scan", "make mould","cast","milling","oven dry"]

			# Automatically create respective tasks for 
			case @case.case_type
				when 1
					crowns.each do |c|
					@task=@case.tasks.new(description:c)
					@task.save
				end
				when 2
					retainers.each do |r|
					@task=@case.tasks.new(description:r)
					@task.save
				end
				when 3
					braces.each do |b|
					@task=@case.tasks.new(description:b)
					@task.save
				end
				when 4
					babies.each do |bb|
					@task=@case.tasks.new(description:bb)
					@task.save
				end
			end

			redirect_to case_path(@case)

		else
			flash[:info] = "Whoopss, something went wrong. Case was not created!"
			render template: "/cases/new"
		end

	end

	# Display page for each case
	def show
		@case=Case.find(params[:id])
		@tasks = @case.tasks
	end

	def new 
		@case=Case.new
	end

	def edit
	end

	def destroy
	end


private 

	def get_params
		params.require(:case).permit(:serial_number,:case_type)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def new
	end

	def create
		
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :verify_authenticity_token, :only => [:log_in]

	def index
	end

	# This is the QR code api that sends the request
	def create_qrcode
		@qr = RQRCode::QRCode.new( qr_code_params[:text], size: 4)
		byebug 
	end

	def new
		@user=User.new
	end

	def create
		user= User.new(get_params)

		if user.save
			redirect_to root_path
			flash[:success] = "User successfully created! Log in to continue.."
		else 
			flash[:info] = "Whoopss, something went wrong. User was not created!"
			render template: "/users/new"
		end	
	end

	# Sign in section
	def log_in
		email = signin_params[:email]

		if user = User.find_by(email: email)
			# if email found, then authenticate password
			input_password = signin_params[:password]
			
			if user.authenticate(input_password)
				# create session
				session[:user_id]=user.id
				redirect_to user_path(user)
				flash[:success] = "Successful Log-in"
			else
				flash[:info] ="Wrong password. Please try again."
			end

		else
			redirect_to root_path
			flash[:info] = "Email not found. Please sign up."
		end

		# check existance of email
		# authenticate password
		# create sessions
	end

	def log_out
		
		session[:user_id]=nil
		redirect_to root_path
	end

	def show
		@user= User.find(params[:id])
		# Cases created by user
		@cases=@user.cases

	end

	def update
	end

	def destroy
	end

private
  def qr_code_params
    params.require(:qr_code).permit(:text)
  end

  def get_params
  	params.require(:user).permit(:first_name, :last_name, :position, :email,:password)
  end

  def signin_params
  	params.permit(:email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cases/new.html.erb
<div class="container margin-top">
	<h2>Create a new case :)</h2>
</div>


<div class= "container">

	<%= form_for Case.new do |form| %>

		<!-- Serial number would follow the case_id with case_type, this would be done in controller -->
		
		<!-- User automatically get registered -->
		<!-- User selects from the possible case types, which would be automatically linked to all its unique tasks -->
		<!--  -->
<!-- 		<div class="form-group">
			<label for="serial_number">Serial Number*</label>
			<%= form.text_field :serial_number, class: 'form-control', placeholder: 'Serial Number' %>
		</div> -->

		<div class="form-group">	  
			<label for="case_type">Select list (select one):</label>
			<%= form.select :case_type, options_for_select([['Crowns','1'], ['Retainers','2'],['Brace','3'],['Babies','4']]) %>
		</div>

		<div class="submit-field">
			<%= form.submit class:"btn btn-primary" %>
		</div>
		
	<%end%>

</div>

app/views/cases/show.html.erb
<div class="container margin-top">
	<!-- Trying to create profile page for user. -->
	<h2>Case <%=@case.id%></h2>
</div>

<div class= "container">
	<h3>Procedures for 
		<%case @case.case_type%>
			<%when 0%>
			Sunshines
			<%when 1%>
			Crowns
			<%when 2%>
			Retainer
			<%when 3%>
			Brace
			<%when 4%>
			Babies
		<%else%>
			Error: case type not recognised.
		<%end%>
	.</h3>
	<br/>
</div>

<!-- Show all tasks for the case -->
<div class="container">
	<%@tasks.each_with_index do |tasks,i|%>
		Task <%=i+1%> : <%=tasks.description%><br/>
	<%end%>
</div>

<hr/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QR Code Scanner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light navbar-color">
      <!-- Logo to the nav bar -->
    <a class="navbar-brand" href="/">
      <img src="/" height="55" class="d-inline-block align-top" alt=""> </a>  

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/users/<%=current_user.id%>">Profile<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <!-- This is for user to search up cases based on the QR -->
              <a class="nav-link" href="/">Scan QR<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <div class="nav-link">
              <%=button_to "Sign Out",log_out_path%>
            </div>
          </li>
          <%else%>
            <%=link_to "Sign Up", new_user_path%>
          <%end%>
      </ul>
    </div>
  </nav>

    <!-- This is for flashing status if you ever need it :) -->
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class= "container">

  <div class="form-group">
    <label for="first_name">First Name*</label>
    <%= form.text_field :first_name, class: 'form-control', placeholder: 'Enter First Name' %>
  </div>

  <div class="form-group">
    <label for="last_name" >Last Name*</label>
    <%= form.text_field :last_name, class: 'form-control', placeholder: 'Enter Last Name' %>
  </div>

  <div class="form-group">
    <label for="position">Position</label>
    <%= form.text_field :position, class: 'form-control', placeholder: 'Position/Role' %>
    <%= form.select :position, options_for_select([['Technician'], ['','2'],['Boobies','3'],['Babies','4']]) %>
    <small>
      Future improvements : Only verified and assigned by super admin.
    </small>
  </div>

  <div class="form-group">
    <label for="email">Email*</label>
    <%= form.text_field :email, class: 'form-control', placeholder: 'Email' %>
  </div>

  <div class="form-group">
    <label for="password">Password*</label>
    <%= form.password_field :password, class: 'form-control', placeholder: 'Enter Password' %>
    <small>
      Minimum 6 chars.
    </small>
  </div>
  
</div>

app/views/users/create_qrcode.html.erb
<h1>This is your generated QR code</h1>
<div>
	<%=link_to "Home",root_path%>
</div>

<div class="qr-square-box">
	<table class="qr-code">
	<% @qr.modules.each_index do |x| %>
	  <tr>
	  <% @qr.modules.each_index do |y| %>
	   <% if @qr.dark?(x,y) %>
	    <td class="black"/>
	   <% else %>
	    <td class="white"/>
	   <% end %>
	  <% end %>
	  </tr>
	<% end %>
	</table>
</div>

app/views/users/index.html.erb
<!-- Home button -->
<div class="container">
	<%=link_to "Home", root_path%>
</div>


<div class="container">
	<%=link_to "Create a Case", new_case_path%>
</div>
<div class= "container">
	<h1>Hello World :)</h1>
	<h3>This is Melissa's QR Code Maker and Decoder Trial</h3>
</div>

<hr/>
<div class= "container">
	<!-- Easy to embed a QR code -->
	<img src="https://api.qrserver.com/v1/create-qr-code/?data=HelloWorld&amp;size=100x100" alt="" title="" />
</div>

<hr/>

<div class="container">
	<h2>QR Code Maker</h2>
	<p>This can be place inside case object "create", so a QR code is created if a case object is created!</p>
	<%= form_for :qr_code, url: create_qrcode_path do |f| %>
	  <%= f.label :text %>
	  <%= f.text_field :text %>
	  <%= f.submit %>
	<% end %>

</div>

<hr/>

<div class="container">

	<h2>QR Code Reader</h2>

	<input type=text class=qrcode-text>
	<label class=qrcode-text-btn>
	   <input type=file
	         accept="image/*"
	         capture=environment
	         tabindex=-1>
	</label>

</div>

app/views/users/new.html.erb
<div class= "container">

	<h3>Sign Up here! :)</h3>	

	<div class= "container full-height">
	
    <%= form_for User.new do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit class:"btn btn-primary" %>
      </div>

    <% end %>

</div>

app/views/users/show.html.erb
<!-- After User Log-in, User will be directed to User show page which would be the Dashboard -->

<div class="container margin-top">
	<h2>Welcome back <%=@user.first_name%>.</h2>
</div>

<hr/>

<div class= "container thin-border-box top-margin div-width">
	<table style= "width:100%">
		<tr>
			<td><strong>Full Name:</strong></td>
			<td><%=@user.first_name%> <%=@user.last_name%></td>
		</tr>
		<tr>
			<td><strong>Email:</td>
			<td><%=@user.email%></td>
		</tr>
	</table>
</div>

<hr/>

<div class="container">
	<%=link_to "Create a Case", new_case_path%>
</div>


<hr/>

<div class="container">
	You have created <%=@cases.length%> cases since you boarded.
	<br/>
	<table>
		<%@cases.each_with_index do |c,i|%>
		<tr>
			<td><%=i+1%>:</td>
			<td><%=c.serial_number%></td>
			<td><%=link_to "View",case_path(c)%></td>
		</tr>

		<%end%>
	</table>
	
</div>

app/views/welcome/index.html.erb
<body class ="welcome-body">

<div class= "container">
	<h1>Welcome to the QR Code Homepage</h1>
</div>

<!-- Login form, if logged in then dont show -->
<%if logged_in? == false%>
<div class="container margin-top">

	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<!-- div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div> -->
			</div>
			<div class="card-body">
				<form action="/log_in" method="post">
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username" name="email">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password" name="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>

			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="/users/new">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password? Doesn't work yet!</a>
				</div>
			</div>
		</div>
	</div>
</div>
<%else%>
	<div class="container"> 
		<p>Hello <%=current_user.first_name%></p>
	</div>
<%end%>



<div class=" container container-tempo">
	<p>Click below link to go to QR code scanner!</p>
	<%=link_to "QR Scanner", users_path%>
</div>

</body>